stages:
    - test

image: python:3.6-alpine

test:
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - ./vrtpktgen -v test.yaml

lint:
    stage: test
    before_script:
        - apk add gcc musl-dev
        - pip install pylint
    script:
        - pylint vrtgen
