stages:
    - test

image: python:3.6-alpine

test:
    stage: test
    before_script:
        - pip install .
        - pip install pytest
    script:
        - pytest --color=yes

lint:
    stage: test
    before_script:
        - apk add gcc musl-dev
        - pip install .
        - pip install pylint pylint_junit
    script:
      # ensure output goes to stdout and the xml file
      # the stdout/err is useful to see logs in the gitlab UI
      - pylint -f colorized --output-format=pylint_junit.JUnitReporter src/ | tee linter.xml
    artifacts:
      paths:
        - linter.xml
      reports:
        junit: linter.xml
    except:
         - develop

test:cpp:
    stage: test
    before_script:
        - apk add g++ make cmake
        - pip install .
        - cd cpp
        - pip install .
        - cmake -B build .
        - cd build
        - export MAKEFLAGS="-j$(nproc)"
    script:
        - make check TEST_OPTIONS="-s --use-colour=yes"

