stages:
    - test
    - package

image: python:3.6-alpine

test:
    stage: test
    before_script:
        - pip install .
        - pip install pytest
    script:
        - pytest --color=yes --junit-xml=vrtgen-tests.xml
    artifacts:
        paths:
            - vrtgen-tests.xml
        reports:
            junit: vrtgen-tests.xml

lint:
    stage: test
    before_script:
        - apk add gcc musl-dev
        - pip install .
        - pip install pylint
    script:
        # Tell Pylint not to exit with a non-zero status for GitLab's benefit.
        # Unfortunately, even if the command completely fails (e.g., invalid
        # path) it still exits with 0.
        - pylint -f colorized --exit-zero src/

test:cpp:
    stage: test
    before_script:
        - apk add g++ make cmake
        - pip install .
        - cd cpp
        - pip install .
        - cmake -B build -DJUNIT_OUTPUT=yes .
        - cd build
        - export MAKEFLAGS="-j$(nproc)"
    script:
        - make check
    artifacts:
        paths:
            - cpp/build/*-results.xml
        reports:
            junit: cpp/build/*-results.xml

# Build release RPMs
rpmbuild:
    stage: package
    image: centos:7
    before_script:
        - yum install -y epel-release rpm-build python3
        - yum install -y cmake3 gcc-c++ make
    script:
        # Base package
        - python3 setup.py bdist_rpm
        # C++ codegen plugin
        - cd cpp
        - python3 setup.py bdist_rpm --dist-dir ../dist
        - cd ..
        # C++ library packaging (requires installing Python RPMs)
        - yum install -y dist/vrtgen-*.noarch.rpm
        - cmake3 -B release cpp
        - cd release
        - cpack3 -G RPM
        - mv *.rpm ../dist
    artifacts:
        paths:
            - dist/*.rpm
    only:
        - tags
