#!/usr/bin/python3

__version__ = '0.1'

import logging
import argparse
import sys

from vrtgen.parser import FileParser

logging.basicConfig()

class NullGenerator:
    def generate(self, packet):
        pass

if __name__ == '__main__':
    arg_parser = argparse.ArgumentParser(description='Generate VITA 49.2 packet classes.')
    arg_parser.add_argument('filename', nargs='+', help='VRT YAML definition file')
    arg_parser.add_argument('-v', '--verbose', action='store_true', default=False,
                            help='display debug messages')
    arg_parser.add_argument('--version', action='version', version='%(prog)s '+__version__)
    arg_parser.add_argument('-b', '--backend', help='backend code generator to target')

    args = arg_parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.backend == 'bindump':
        from vrtgen.backend.bindump import BinaryDumper
        generator = BinaryDumper()
    elif args.backend == 'cpp':
        from vrtgen.backend.cpp import CppGenerator
        generator = CppGenerator()
    else:
        generator = NullGenerator()

    for filename in args.filename:
        logging.debug('Parsing %s', filename)
        for packet in FileParser().parse(filename):
            generator.generate(packet)
