ConfigureTuner:
  control:
    timestamp:
      integer: utc
      fractional: picoseconds
    controllee: word
    controller: word
    permit:
      partial: true
      warnings: true
      errors: false
    action: execute
    acknowledge:
      negative: false
      execution: true
      warnings: true
      errors: true
    cif0:
      bandwidth: optional
      rf-reference-frequency: optional
      gain: optional
      sample-rate: optional
    cif1:
      discrete-io-32:
        fields:
          - Stream Enable: optional
